# Generated by Django 2.2 on 2021-03-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210325_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoventa',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha de entrega'),
        ),
    ]
