# Generated by Django 2.2 on 2021-03-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20201230_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_column='creado', verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_column='creado', verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_column='creado', verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='parteimpresion',
            name='create',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
    ]
