# Generated by Django 2.2 on 2021-03-16 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20210314_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteimpresion',
            name='ayudante1ero',
            field=models.ForeignKey(db_column='ayudante1er', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ayudante1er', to=settings.AUTH_USER_MODEL, verbose_name='Primer ayudante'),
        ),
        migrations.AlterField(
            model_name='parteimpresion',
            name='ayudante2do',
            field=models.ForeignKey(db_column='ayudante2do', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ayudante2do', to=settings.AUTH_USER_MODEL, verbose_name='Segundo ayudante'),
        ),
        migrations.AlterField(
            model_name='parteimpresion',
            name='maquinista',
            field=models.ForeignKey(db_column='maquinista', on_delete=django.db.models.deletion.DO_NOTHING, related_name='maquinista', to=settings.AUTH_USER_MODEL, verbose_name='Maquinista'),
        ),
        migrations.AlterField(
            model_name='parteimpresion',
            name='supervisor',
            field=models.ForeignKey(db_column='supervisor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.DeleteModel(
            name='CategoriasUsuario',
        ),
    ]
