# Generated by Django 3.0.5 on 2021-03-20 21:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0005_auto_20210315_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionesGles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de creación')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones generales')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin observación')),
            ],
            options={
                'verbose_name': 'Observación general',
                'verbose_name_plural': 'Observaciones generales',
                'db_table': 'observaciones_gles',
            },
        ),
        migrations.CreateModel(
            name='ObsMantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de creación')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones del mecánico')),
                ('mecanico', models.ForeignKey(db_column='mecanico', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mecanico', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico')),
            ],
            options={
                'verbose_name': 'Observación mantenimiento',
                'verbose_name_plural': 'Observaciones mantenimiento',
                'db_table': 'observaciones_mant',
            },
        ),
        migrations.AddField(
            model_name='parteimpresion',
            name='observacion_gral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control.ObservacionesGles'),
            preserve_default=False,
        ),
    ]
