# Generated by Django 3.0.5 on 2021-03-22 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20210320_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteimpresion',
            name='observacion_mant',
            field=models.ManyToManyField(blank=True, db_column='obs_mant', related_name='observacion_mant', to='control.ObsMantenimiento', verbose_name='Observaciones de mantenimiento'),
        ),
        migrations.RemoveField(
            model_name='parteimpresion',
            name='observacion_gral',
        ),
        migrations.AddField(
            model_name='parteimpresion',
            name='observacion_gral',
            field=models.ManyToManyField(blank=True, db_column='obs_gles', related_name='observacion_gral', to='control.ObservacionesGles', verbose_name='Observaciones generales'),
        ),
        migrations.CreateModel(
            name='OrdenesProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Fecha creaciín')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('kg_prod', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Kg. producidos')),
                ('metros_prod', models.IntegerField(verbose_name='Metros producidos')),
                ('parte_impresion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.ParteImpresion')),
            ],
        ),
    ]
