# Generated by Django 3.0.5 on 2021-03-22 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20210321_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenesproduccion',
            name='parte_impresion',
        ),
        migrations.RemoveField(
            model_name='parteimpresion',
            name='fichaTecnica',
        ),
        migrations.RemoveField(
            model_name='parteimpresion',
            name='impresora',
        ),
        migrations.AddField(
            model_name='ordenesproduccion',
            name='fichaTecnica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control.FichaTecnica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenesproduccion',
            name='impresora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control.Impresora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenesproduccion',
            name='create',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='ordenesproduccion',
            name='kg_prod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Kg. a producir'),
        ),
        migrations.AlterField(
            model_name='ordenesproduccion',
            name='metros_prod',
            field=models.IntegerField(verbose_name='Metros a producir'),
        ),
    ]
