# Generated by Django 3.0.5 on 2021-03-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20210321_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenesproduccion',
            options={'verbose_name': 'Ordenes de producción', 'verbose_name_plural': 'Ordenes de producción'},
        ),
        migrations.AlterModelTable(
            name='ordenesproduccion',
            table='orden_produccion',
        ),
    ]
