# Generated by Django 3.0.5 on 2021-03-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20210321_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenesproduccion',
            name='estado',
        ),
    ]
