# Generated by Django 3.0.5 on 2020-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20201229_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impresora',
            name='delete',
        ),
        migrations.AlterField(
            model_name='impresora',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
